
global:
  redis:
    enabled: true
serviceAccount:
  # Specifies whether a service account should be created
  create: true

replicas: 1

ingress:
  enabled: false

service:
    ##  Redis Sentinel Service type
    type: ClusterIP
    sentinelPort: 26379
    redisPort: 6379

annotations: {}
